# ============================================================================
# import_new_audio.py -- bring ONLY the new audio-upgrade WAVs into UE.
# ----------------------------------------------------------------------------
# A surgical companion to import_art.py: it imports just the five new World
# audio-upgrade sounds (generated by synth_audio.py) into /Game/Art/Audio,
# WITHOUT re-importing every mesh/material (so it adds no working-tree churn to
# the rest of /Game/Art). Same SoundWave + looping rules as import_art.py.
#
# Run (default RenderOffscreen mode -- NOT -nullrhi; this is an asset edit but
# we keep the GPU path to match the project's import convention):
#   powershell -File Scripts/run_pyscript.ps1 -Script ..\PyScripts\import_new_audio.py
# ============================================================================

import os
import traceback

import unreal

PROJECT_DIR   = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
AUDIO_SRC_DIR = os.path.join(PROJECT_DIR, "ArtSource", "audio")
AUDIO_DEST    = "/Game/Art/Audio"

# The five new assets from the World audio upgrade (stems, no extension).
NEW_STEMS = [
    "music_city_loop_v2",
    "music_victory_sting",
    "sfx_flag_raise",
    "sfx_capture",
    "sfx_enemy_defeat",
]

asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
eal = unreal.EditorAssetLibrary


def log(msg):
    print("[import_new_audio] {}".format(msg))
    try:
        unreal.log("[import_new_audio] {}".format(msg))
    except Exception:
        pass


def import_wav(stem):
    """Import one ArtSource/audio/<stem>.wav as a SoundWave; loop if name ends in _loop."""
    src = os.path.join(AUDIO_SRC_DIR, stem + ".wav")
    target = AUDIO_DEST + "/" + stem
    if not os.path.isfile(src):
        log("MISSING source: {}".format(src))
        return False
    try:
        if eal.does_asset_exist(target):
            eal.delete_asset(target)   # idempotent: rebuild from the fresh .wav

        task = unreal.AssetImportTask()
        task.set_editor_property("automated", True)
        task.set_editor_property("filename", src)
        task.set_editor_property("destination_path", AUDIO_DEST)
        task.set_editor_property("destination_name", stem)
        task.set_editor_property("replace_existing", True)
        task.set_editor_property("save", True)
        task.set_editor_property("options", None)
        asset_tools.import_asset_tasks([task])

        sound = eal.load_asset(target)
        if not isinstance(sound, unreal.SoundWave):
            log("FAIL {}: imported asset is not a SoundWave".format(stem))
            return False
        if stem.lower().endswith("_loop") or stem.lower().endswith("_loop_v2"):
            sound.set_editor_property("looping", True)
            log("imported (LOOPING): {}".format(target))
        else:
            log("imported: {}".format(target))
        eal.save_loaded_asset(sound)
        return True
    except Exception as e:
        log("FAIL {}: {}".format(stem, e))
        traceback.print_exc()
        return False


def main():
    eal.make_directory(AUDIO_DEST)
    log("source dir: {}".format(AUDIO_SRC_DIR))
    ok = 0
    for stem in NEW_STEMS:
        if import_wav(stem):
            ok += 1
    log("=" * 50)
    log("IMPORTED {}/{} new audio assets".format(ok, len(NEW_STEMS)))
    log("=" * 50)


if __name__ == "__main__":
    main()
